package object.dao;

import object.model.Website;
import org.hibernate.SessionFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.orm.hibernate4.HibernateTemplate;

import javax.sql.DataSource;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by 4535992 on 01/04/2015.
 */
public interface IWebsiteDao extends IGenericDao<Website> {

    void setDriverManager(String driver, String typeDb, String host, String port, String user, String pass, String database);
    void setTable(String nameOfTable);
    void setJdbcTemplate(JdbcTemplate jdbcTemplate);
    void setHibernateTemplate(HibernateTemplate ht);
    void setHibernateTemplate(SessionFactory sessionFactory);
    void setDataSource(DataSource ds);
    void loadSpringConfig(String filePathXml);
    void loadHibernateConfig(String filePathXml);


    void create() throws Exception;
    void create(boolean erase) throws Exception;
    boolean verifyDuplicate(String columnWhereName, String valueWhereName);

    int getCount();

    void deleteAll();

    Number getAutoGeneratedKey(String idColumn);

    List<Website> selectAll();
    List<String> selectAllString(String column, String limit, String offset);

    //method to save
    void saveH(Website g);

    //method to update
    void updateH(Website g);

    //method to delete
    void deleteH(Website g);

    //method to return one of given id
    Website getHByColumn(String column);

    //method to return all
    List<Website> getAllH();

    List<URL> selectAllUrl(String column_table_input, String s, String s1) throws MalformedURLException;
}
